/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.vistas;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.table.DefaultTableModel;

import com.example.EstructurasDeDatos.Cola;
import com.example.Model.Ticket;
import com.example.Service.GestionColasTickets;

/**
 *
 * @author JUAN DAVID FUENTES
 */
public class ColaTickets extends javax.swing.JFrame {

        private GestionColasTickets gestionColasTickets = new GestionColasTickets();

        /**
         * Creates new form ColaTickets
         */
        public ColaTickets() {
                gestionColasTickets.cargarColasDesdeJSON("cola_tickets.json");
                this.gestionColasTickets = gestionColasTickets;
                gestionColasTickets.imprimirColas();
                initComponents();
                setLocationRelativeTo(null);

        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jPanel2 = new javax.swing.JPanel();
                jLabel3 = new javax.swing.JLabel();
                jLabel7 = new javax.swing.JLabel();
                jButtonBuscar = new javax.swing.JButton();
                jScrollPane1 = new javax.swing.JScrollPane();
                jTable1 = new javax.swing.JTable();
                jLabel1 = new javax.swing.JLabel();
                jLabel9 = new javax.swing.JLabel();
                jComboBoxTipoExamen = new javax.swing.JComboBox<>();
                jLabel4 = new javax.swing.JLabel();
                jScrollPane3 = new javax.swing.JScrollPane();
                jTextArea2 = new javax.swing.JTextArea();
                jLabel2 = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jPanel1.setBackground(new java.awt.Color(255, 255, 255));
                jPanel1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
                jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jPanel2.setBackground(new java.awt.Color(42, 39, 69));

                jLabel3.setBackground(new java.awt.Color(42, 49, 69));
                jLabel3.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
                jLabel3.setForeground(new java.awt.Color(255, 255, 255));
                jLabel3.setText("Cola Tickets");

                jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\JUAN DAVID FUENTES\\Desktop\\png\\caduceo.png")); // NOI18N
                jLabel7.setToolTipText("");

                jButtonBuscar.setBackground(new java.awt.Color(42, 39, 69));
                jButtonBuscar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
                jButtonBuscar.setForeground(new java.awt.Color(255, 255, 255));
                jButtonBuscar.setText("Desencolar");
                jButtonBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                String motivoSeleccionado = (String) jComboBoxTipoExamen.getSelectedItem();
                                gestionColasTickets.desencolarTicket(motivoSeleccionado); // Desencolar el próximo
                                                                                          // ticket
                                mostrarTicketsPorMotivo(motivoSeleccionado); // Mostrar los tickets actualizados después
                                                                             // de desencolar
                        }
                });

                jTable1.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {
                                                { null, null, null, null, null, null },
                                                { null, null, null, null, null, null },
                                                { null, null, null, null, null, null },
                                                { null, null, null, null, null, null }
                                },
                                new String[] {
                                                "ID", "Nombre", "Apellido", "Edad", "Identificacíon", "Teléfono"
                                }));
                jScrollPane1.setViewportView(jTable1);

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(jLabel3)
                                                                .addGap(23, 23, 23))
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(19, 19, 19)
                                                                .addComponent(jScrollPane1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                518,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 23, Short.MAX_VALUE))
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel7)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(jButtonBuscar,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                120,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(36, 36, 36)));
                jPanel2Layout.setVerticalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel3,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                71,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel2Layout
                                                                                                .createSequentialGroup()
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(jScrollPane1,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                266,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(jLabel7)
                                                                                                .addContainerGap(17,
                                                                                                                Short.MAX_VALUE))
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                jPanel2Layout.createSequentialGroup()
                                                                                                                .addPreferredGap(
                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(jButtonBuscar,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                30,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addGap(94, 94, 94)))));

                jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 560, 500));

                jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
                jLabel1.setText("Proximo Turno");
                jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, 50));

                jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\JUAN DAVID FUENTES\\Desktop\\png\\24px.png")); // NOI18N
                jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

                jComboBoxTipoExamen.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
                jComboBoxTipoExamen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Examen físico",
                                "Exámenes de laboratorio", "Imágenes diagnósticas", "Pruebas de función",
                                "Exámenes endoscópicos", "Exámenes genéticos", "Exámenes de imagenología funcional",
                                "Exámenes de diagnóstico por ultrasonido", " " }));
                jPanel1.add(jComboBoxTipoExamen, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 190, -1));
                jComboBoxTipoExamen.addActionListener(new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent e) {
                                mostrarTicketsPorMotivo((String) jComboBoxTipoExamen.getSelectedItem());
                        }
                });

                jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
                jLabel4.setText("Motivo");
                jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

                jScrollPane3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

                jTextArea2.setEditable(false);
                jTextArea2.setBackground(new java.awt.Color(42, 39, 69));
                jTextArea2.setColumns(20);
                jTextArea2.setForeground(new java.awt.Color(51, 255, 0));
                jTextArea2.setRows(5);
                jScrollPane3.setViewportView(jTextArea2);

                jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 190, 190));

                jLabel2.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
                jLabel2.setText("Citas");
                jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, 50));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

                pack();
        }// </editor-fold>

        private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {
                // TODO add your handling code here:
        }

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(ColaTickets.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(ColaTickets.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(ColaTickets.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(ColaTickets.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new ColaTickets().setVisible(true);
                        }
                });
        }

        private void mostrarTicketsPorMotivo(String motivo) {
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.setRowCount(0); // Limpiar la tabla antes de cargar los datos nuevos

                if (motivo != null) {
                        Cola<Ticket> colaOriginal = gestionColasTickets.getColaPorMotivo(motivo);
                        if (colaOriginal != null) {
                                // Mostrar el ticket más próximo aparte y cambiar su color
                                Ticket proximoTicket = colaOriginal.peek();
                                if (proximoTicket != null) {
                                        jTextArea2.setText(
                                                        proximoTicket.toString() + "\n\n");
                                }

                                // Crear una cola temporal para mostrar los tickets
                                Cola<Ticket> colaTemporal = new Cola<>();
                                gestionColasTickets.cargarColasDesdeJSON("cola_tickets.json");

                                // Copiar los elementos de la cola original a la cola temporal
                                while (!colaOriginal.estaVacia()) {
                                        colaTemporal.enqueue(colaOriginal.dequeue());
                                }

                                // Mostrar los tickets en la tabla
                                while (!colaTemporal.estaVacia()) {
                                        Ticket ticket = colaTemporal.dequeue();
                                        model.addRow(new Object[] { ticket.getIdentificador(), ticket.getMotivoCita(),
                                                        ticket.getTurno(),
                                                        ticket.isEstadoPago(), ticket.getValor() });
                                }
                        }
                }
        }

        // Variables declaration - do not modify
        private javax.swing.JButton jButtonBuscar;
        private javax.swing.JComboBox<String> jComboBoxTipoExamen;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane3;
        private javax.swing.JTable jTable1;
        private javax.swing.JTextArea jTextArea2;
        // End of variables declaration
}
