/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.vistas;

import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;

import javax.swing.JOptionPane;
import javax.swing.JTextField;

import com.example.Model.Paciente;
import com.example.Service.GestionPacientesImp;

/**
 *
 * @author JUAN DAVID FUENTES
 */
public class RegistroPaciente extends javax.swing.JFrame {

    GestionPacientesImp gestionPacientesImp = new GestionPacientesImp();

    /**
     * Creates new form RegistroPaciente
     */
    public RegistroPaciente() {
        initComponents();
        setLocationRelativeTo(null);
        gestionPacientesImp.cargarPacientesDesdeJSON("pacientes.json");
        jTextFieldNombre.addFocusListener(new ReiniciarCampoTexto("Ingrese Nombre", jTextFieldNombre));
        jTextFieldApellido.addFocusListener(new ReiniciarCampoTexto("Ingrese Apellido", jTextFieldApellido));
        jTextFieldEdad.addFocusListener(new ReiniciarCampoTexto("Ingrese Edad", jTextFieldEdad));
        jTextFieldIdentificacion
                .addFocusListener(new ReiniciarCampoTexto("Ingrese Identificación", jTextFieldIdentificacion));
        jTextFieldTelefono.addFocusListener(new ReiniciarCampoTexto("Ingrese Telefono", jTextFieldTelefono));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        labelTelefono = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        botonRegistrar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jTextFieldTelefono = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        labelEdad = new javax.swing.JLabel();
        labelApellido = new javax.swing.JLabel();
        labelId = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jTextFieldApellido = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldEdad = new javax.swing.JTextField();
        jTextFieldIdentificacion = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(42, 39, 69));

        jLabel3.setBackground(new java.awt.Color(42, 49, 69));
        jLabel3.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Registro Pacientes");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\JUAN DAVID FUENTES\\Desktop\\png\\caduceo.png")); // NOI18N
        jLabel7.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel7)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 510, 500));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel1.setText("Registro Paciente");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 50));

        labelTelefono.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        labelTelefono.setText("Telefono");
        jPanel1.add(labelTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        labelNombre.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        labelNombre.setText("Nombre");
        jPanel1.add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, 20));

        botonRegistrar.setBackground(new java.awt.Color(42, 39, 69));
        botonRegistrar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        botonRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        botonRegistrar.setText("Registrar");
        botonRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                String nombres = jTextFieldNombre.getText();
                String apellidos = jTextFieldApellido.getText();
                String edadStr = jTextFieldEdad.getText();
                String identificacion = jTextFieldIdentificacion.getText();
                String numeroTelefono = jTextFieldTelefono.getText();

                if (!numeroTelefono.matches("\\d{10}")) {
                    JOptionPane.showMessageDialog(null,
                            "El número de teléfono debe tener el formato 3#########.",
                            "Error en el número de teléfono", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                if (!identificacion.matches("\\d{9,10}")) {
                    JOptionPane.showMessageDialog(null,
                            "La identificación debe tener entre 9 y 10 dígitos.",
                            "Error en la identificación", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                int edad;
                try {
                    edad = Integer.parseInt(edadStr);
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(null,
                            "La edad debe ser un número válido.",
                            "Error en la edad", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                Paciente nuevoPaciente = new Paciente(nombres, apellidos, edad, identificacion, numeroTelefono);

                gestionPacientesImp.crearPaciente(nuevoPaciente);

                jTextFieldNombre.setText("");
                jTextFieldApellido.setText("");
                jTextFieldEdad.setText("");
                jTextFieldIdentificacion.setText("");
                jTextFieldTelefono.setText("");

                JOptionPane.showMessageDialog(null,
                        "Se ha creado correctamente el paciente:\n" +
                                nuevoPaciente.obtenerInformacion() +
                                "\nID Historia Clínica: " + nuevoPaciente.getIdHistoriaClinica(),
                        "Paciente creado", JOptionPane.INFORMATION_MESSAGE);
            }
        });
        jPanel1.add(botonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 120, 30));

        jSeparator2.setForeground(new java.awt.Color(42, 39, 69));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 230, 10));

        jTextFieldTelefono.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldTelefono.setText("Ingrese Telefono");
        jTextFieldTelefono.setToolTipText("");
        jTextFieldTelefono.setBorder(null);
        jTextFieldTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTelefonoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 210, 20));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\JUAN DAVID FUENTES\\Desktop\\png\\24px.png")); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        labelEdad.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        labelEdad.setText("Edad");
        jPanel1.add(labelEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        labelApellido.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        labelApellido.setText("Apellido");
        jPanel1.add(labelApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        labelId.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        labelId.setText("Identificación");
        jPanel1.add(labelId, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jSeparator3.setForeground(new java.awt.Color(42, 39, 69));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 230, 10));

        jSeparator4.setForeground(new java.awt.Color(42, 39, 69));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 230, 10));

        jSeparator5.setForeground(new java.awt.Color(42, 39, 69));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 230, 10));

        jTextFieldApellido.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldApellido.setText("Ingrese Apellido");
        jTextFieldApellido.setToolTipText("");
        jTextFieldApellido.setBorder(null);
        jTextFieldApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApellidoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 210, 20));

        jTextFieldNombre.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldNombre.setText("Ingrese Nombre");
        jTextFieldNombre.setToolTipText("");
        jTextFieldNombre.setBorder(null);
        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 210, 20));

        jTextFieldEdad.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldEdad.setText("Ingrese Edad");
        jTextFieldEdad.setToolTipText("");
        jTextFieldEdad.setBorder(null);
        jTextFieldEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEdadActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 210, 20));

        jTextFieldIdentificacion.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldIdentificacion.setText("Ingrese Identificación");
        jTextFieldIdentificacion.setToolTipText("");
        jTextFieldIdentificacion.setBorder(null);
        jTextFieldIdentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdentificacionActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 210, 20));

        jSeparator6.setForeground(new java.awt.Color(42, 39, 69));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 230, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        pack();
    }// </editor-fold>

    private void botonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jTextFieldTelefonoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jTextFieldApellidoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jTextFieldEdadActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jTextFieldIdentificacionActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroPaciente.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroPaciente.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroPaciente.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroPaciente.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroPaciente().setVisible(true);
            }
        });
    }

    class ReiniciarCampoTexto implements FocusListener {
        private String textoInicial;
        private JTextField campoTexto;

        public ReiniciarCampoTexto(String textoInicial, JTextField campoTexto) {
            this.textoInicial = textoInicial;
            this.campoTexto = campoTexto;
        }

        @Override
        public void focusGained(FocusEvent e) {
            // Si el texto actual del campo de texto es igual al texto inicial, borrarlo
            if (campoTexto.getText().equals(textoInicial)) {
                campoTexto.setText("");
            }
        }

        @Override
        public void focusLost(FocusEvent e) {
            // Si el campo de texto está vacío al perder el foco, restaurar el texto inicial
            if (campoTexto.getText().isEmpty()) {
                campoTexto.setText(textoInicial);
            }
        }
    }

    // Variables declaration - do not modify
    private javax.swing.JButton botonRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldEdad;
    private javax.swing.JTextField jTextFieldIdentificacion;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldTelefono;
    private javax.swing.JLabel labelApellido;
    private javax.swing.JLabel labelEdad;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelTelefono;
    // End of variables declaration
}
